### PR TITLE
Fix CORS handling for passthrough gateways

### LINKED ISSUE #16: .passthrough() OPTIONS integration does not work for XHR requests
Because [hookshot sets access-control-allow-headers to *](https://github.com/mapbox/hookshot/blob/master/index.js#L175), and this is not supported by XHR in some browsers.

However, [fetch appears to allow it](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

### PR DESCRIPTION
**Pull request by davidtheclark**
Adds a Lambda function that receives all passthrough requests, handles OPTIONS requests and forward POST requests to the user's Lambda function; then adjusts the user's response to include
CORS headers.

Closes #16.

I will try to use this (referencing this public branch from `package.json`) and see how it goes. @rclark please let me know if you see any obvious mistakes.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -120,6 +120,45 @@ const Method = (prefix) => ({
...
+    Code: {
+      ZipFile: cf.join('\n', [
+        '"use strict";',
+        'const AWS = require("aws-sdk");',
+        cf.sub('const lambda = new AWS.Lambda({ region: "${AWS::Region}" });'),
+        'module.exports.lambda = (event, context, callback) => {',
+        '  if (event.httpMethod === "OPTIONS") {',
+        '    const response = {',
+        '      statusCode: 200,',
+        '      "Access-Control-Allow-Headers": "Content-Type"',
```
Comment (rclark) [inline index.js]: I think that what we really want to do to make this work is respond with whatever `Access-Control-Allow-Headers` value that the request asked for in the first place. If it's only `Content-Type` in the response, we'll see other requests get blocked.

File: index.js [hunk 2]
```diff
@@ -120,6 +120,45 @@ const Method = (prefix) => ({
...
+        '      "Access-Control-Allow-Methods": "POST, OPTIONS"',
+        '      "Access-Control-Allow-Origin": "*"',
```
Comment (rclark) [inline index.js]: Do these headers need to be in a `.headers` property of the response?

File: index.js [hunk 3]
```diff
@@ -120,6 +120,45 @@ const Method = (prefix) => ({
...
+        '    };',
+        '    callback(null, response);',
+        '    return;',
+        '  }',
+        `  const lambdaParams = { FunctionName: "${lambda}" };`,
+        '  lambda.invoke(lambdaParams, (err, response) => {',
+        '    if (err) return callback(err);',
+        '    if (!response) callback(new Error("Response required"));',
```
Comment (rclark) [inline index.js]: The failure case here could be made more clear to the user -- this would be a fundamental problem with the hookshot user's own lambda function not returning what it has to return. Likely only encountered while initially creating a system / debugging.

File: index.js [hunk 4]
```diff
@@ -120,6 +120,45 @@ const Method = (prefix) => ({
...
+        '    response.headers = response.headers || {};',
+        '    response.headers["Access-Control-Allow-Origin"] = "*";',
+        '    callback(null, response)',
+        '  });',
+        '};'
+      ])
+    },
+    Role: cf.getAtt(`${prefix}FunctionRole`, 'Arn'),
```
Comment (rclark) [inline index.js]: I believe the role will need to be provided with permission to invoke the hookshot user's lambda function.

File: index.js [hunk 5]
```diff
@@ -120,6 +120,45 @@ const Method = (prefix) => ({
...
+    Description: cf.sub('Github webhook for ${AWS::StackName}'),
```
Comment (rclark) [inline index.js]: `Github webhook`? copy-pasta?

File: index.js (hunk 4 above)
Comment (davidtheclark) [reply index.js]: All good points. For this one, though, I don't think I understand what's going on. `AWS::Lambda::Permission`s seem to exist on their own and are not in fact associated with a role. I could create a new one of those and change an existing one to get this:

```js
const PassthroughFunctionPermission = (lambda, prefix) => ({
  Type: 'AWS::Lambda::Permission',
  Properties: {
    FunctionName: cf.ref(`${prefix}PassthroughFunction`),
    Action: 'lambda:InvokeFunction',
    Principal: 'apigateway.amazonaws.com',
    SourceArn: cf.sub(`arn:aws:execute-api:\${AWS::Region}:\${AWS::AccountId}:\${${prefix}Api}/*`)
  }
});

const PassthroughPermission = (lambda, prefix) => ({
  Type: 'AWS::Lambda::Permission',
  Properties: {
    FunctionName: cf.ref(lambda),
    Action: 'lambda:InvokeFunction',
    Principal: 'lambda.amazonaws.com',
    SourceArn: cf.sub(`arn:aws:execute-api:\${AWS::Region}:\${AWS::AccountId}:\${${prefix}Api}/*`)
  }
});
```

But I don't know if that's right or how I would associate any of that with the role. The role seems to already be allowed to deal with Lambda (or something) — is there something else it needs?

Comment (rclark) [reply index.js]: `AWS::Lambda::Permission` is generally used to give some AWS service permission to invoke a lambda function. The first one, gives `apigateway.amazonaws.com` permission to invoke, as long as the invoker is the api-gateway identified by that source arn.

The second one looks wrong. It would give `lambda.amazonaws.com` permission to invoke, as long as the invoker is an api-gateway. That mismatch doesn't seem right.

The `AWS::IAM::Role` that is associated with a Lambda function is where you define _what that lambda function is allowed to do_. In this case, you want to add a statement to that role so that the Passthrough function can invoke the user's function. You shouldn't need an `AWS::Lambda::Permission` to do that.

File: index.js [hunk 6]
```diff
@@ -153,38 +194,56 @@ const OptionsMethod = (prefix) => ({
...
+              ]
+            },
+            {
+              Effect: 'Allow',
+              Action: [
+                'lambda:InvokeFunction'
+              ],
+              Resource: [
+                cf.getAtt(lambda, 'Arn')
+              ]
```
Comment (davidtheclark) [inline index.js]: This doesn't seem to be working as I'd hoped. The `WebhookPassthroughFunction` Lambda throws an error saying this role is not authorized to perform `lambda:InvokeFunction` on my Lambda function. Any suggestions?

Comment (rclark) [reply index.js]: What's the value of `lambda` when you get here? Is is a string? The logical resource name of the hookshot caller's lambda?

Comment (davidtheclark) [reply index.js]: It is the string that I pass into `hookshot.passthrough(HERE)`. I believe that is `The logical resource name of the hookshot caller's lambda`.

A sanitized version of my error message looks like this:
`"User: arn:aws:sts::1234:assumed-role/stack-name-WebhookPassthroughFunctionRo-1234/stack-name-WebhookPassthroughFunction-1234 is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:1234:function:MyLambdaFunctionName"`

**Comment by davidtheclark** [comment]
@rclark: With the latest commit, I think it's working. Key points of confusion for me were:

- Getting the right `FunctionName` into `lambda.invoke` in the passthrough function.
- I wasn't passing any `Payload` to `lambda.invoke` — needed to.
- The `response` from `lambda.invoke` is not the raw value returned by the user's Lambda function: it's wrapped in an object — so I needed to get the `Payload` out of that, and parse it.

So this now works with a Lambda function I've defined that expects it's `event.body` to be the object provided by API Gateway, with `httpMethod`, `body`, etc.

**Review by rclark — APPROVED** [review]
Thanks @davidtheclark ! If you want to merge & publish a new major version that'd be great.
